#!/usr/bin/env bash
# Bash script that displays Best School 10 times
# On the 9th interation,displays Best School and then Hi on a new line.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done